### ISSUE TITLE
date_range_precision_tuning增加后kinaba请求异常

### ISSUE THREAD

**Issue by hebo1982** [infinilabs/gateway#26]
### Description
尝试测试 date_range_precision_tuning，time_precision:6，预设置精度到“秒”，配置之后kibana请求报错了。
去掉改配置后正常。

### Steps to reproduce

```
flow:
  - name: default_flow
    filter:
      - context_regex_replace:
          context: "_ctx.request.uri"
          pattern: "_from=[^&]*&?"
          to: ""
      - date_range_precision_tuning:
          time_precision: 6
      - get_cache:
      - bulk_reshuffle:
          when:
            contains:
              _ctx.request.path: /_bulk
          elasticsearch: prod
          level: node
          fix_null_id: true
      - elasticsearch:
          elasticsearch: prod  #elasticsearch configure reference name
          max_connection_per_node: 1000 #max tcp connection to upstream, default for all nodes
          max_response_size: -1 #default for all nodes
          balancer: weight
          refresh: # refresh upstream nodes list, need to enable this feature to use elasticsearch nodes auto discovery
            enabled: true
            interval: 60s
      - set_cache:
          cache_type: ristretto
          min_response_size: 100
          max_response_size: 1024000
          cache_ttl: 30s
          max_cache_items: 100000
```

### Expected behavior
应该正常按秒格式化kibana请求的时间

### Actual behavior

```
failed to parse date field [2022-08-00T05:59:32.999Z] with format [strict_date_optional_time]: [failed to parse date field [2022-08-00T05:59:32.999Z] with format [strict_date_optional_time]]
```
抓包结果内容：
[kibana_http_400.json.zip](https://github.com/infinilabs/console/files/9314451/kibana_http_400.json.zip)

### Environment
gateway: 1.6.0_SNAPSHOT
es: 7.8.1
kibana: 7.8.1

Build: 
gateway 1.6.0_SNAPSHOT 657 2022-05-31 07:35:13 +0000 UTC 2023-12-31 10:10:10 +0000 UTC 21ec7be5de546f5454b3ccb58b2ce9183cd1ff2d

Operating system and version: 
Centos 7
